name: drop_menu
description: "drop menu"
version: 0.0.1
homepage: https://github.com/Firesoftyazilim/drop_menu

authors:
  - Firesoft<firesoftyazilim@gmail.com>

environment:
  sdk: '>=3.2.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:



license: MIT
